[build]
  base = "frontend"
  command = """
    npm cache clean --force && \
    rm -rf node_modules && \
    npm install --no-audit --prefer-offline && \
    CI=false npm run build
  """
  publish = "build"

[build.environment]
  NODE_VERSION = "16.14.0"
  NPM_VERSION = "8.5.0"
  CI = "false"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 